#!/bin/bash
#$ -cwd
#$ -l mem_free=16G
#$ -l h_rt=4:00:00
#$ -pe smp 8
#$ -t 1-6
#$ -N riri_array_test

declare -a samples=("blank" "NC_1_10_CKDL220001075-1A_HH5FFCCX2_L2_1.fq.gz" "R30min_1_12_CKDL220001077-1A_HH5FFCCX2_L2_1.fq.gz" "R6h_1_10_CKDL220001079-1A_HH5FFCCX2_L2_1.fq.gz" "NC_2_10_CKDL220001076-1A_HH5FFCCX2_L2_1.fq.gz" "R30min_2_10_CKDL220001078-1A_HH5FFCCX2_L2_1.fq.gz" "R6h_2_10_CKDL220001080-1a_HH5FFCCX2_L2_1.fq.gz")
nm=${samples[$SGE_TASK_ID]}
nm=${nm/_L2_1.fq.gz/}
echo "Processing $nm"




# find ./ -iname *.gz -exec mv {} fastq/ \;
out_dir="/wynton/home/javid/chenyuxiang1002/riboseq_processed/ribSeq"
container="/wynton/home/javid/chenyuxiang1002/riri_v0.1.sif"
script_dir="/wynton/home/javid/chenyuxiang1002/riri"
read_dir="/wynton/home/javid/chenyuxiang1002/riboData/RawData/RibosomeProfiling/fastq"

mkdir -p "$out_dir"
cd "$out_dir"

singularity exec "$container" \
  "${script_dir}/riboSee_pipe.sh" \
  --threads 8 \
  --genome_reference "${script_dir}/references/NC_000962_rRNAsMasked.fasta" \
  --GTF_reference "${script_dir}/references/NC_000962.gff" \
  --reads "${read_dir}/${nm}_L2_1.fq.gz" \
  --out_dir "$out_dir" \
  --name "$nm" \
  --strand "reverse" \
  --script_directory "${script_dir}" \
  --fastQC \
  --max_missmatch 2 \
  --min_len 24 \
  --max_len 36 \
  --trim_fasta "${script_dir}/references/adapts.fasta"
  # --cut_adapt "CTGTAGGCACCATCAAT"

# singularity exec /wynton/home/ernst/jdlim/riboseq/riri_v0.1.sif \
#   /wynton/home/ernst/jdlim/riboseq/riri/riboSee_pipe.sh \
#     --get_metrics "/wynton/home/ernst/jdlim/riboseq/"








#!/bin/bash
#$ -cwd
#$ -l mem_free=16G
#$ -l h_rt=4:00:00
#$ -pe smp 8
#$ -t 1-6
#$ -N riboSeek_array_test

declare -a samples=("blank" "NC_1_CKDL220001081-1a_HH5FFCCX2_L2_1.fq.gz" "T30min_1_CKDL220001083-1a_HH5FFCCX2_L2_1.fq.gz" "T6h_1_CKDL220001085-1a_HH5FFCCX2_L2_1.fq.gz" "NC_2_CKDL220001082-1a_HH5FFCCX2_L2_1.fq.gz" "T30min_2_CKDL220001084-1a_HH5FFCCX2_L2_1.fq.gz" "T6h_2_CKDL220001086-1a_HH5FFCCX2_L2_1.fq.gz")
nm=${samples[$SGE_TASK_ID]}
nm=${nm/_L2_1.fq.gz/}
echo "Processing $nm"

# find ./ -iname *.gz -exec mv {} fastq/ \;
out_dir="/wynton/home/javid/chenyuxiang1002/riboseq_processed/rnaSeq"
container="/wynton/home/javid/chenyuxiang1002/riri_v0.1.sif"
script_dir="/wynton/home/javid/chenyuxiang1002/riri"
read_dir="/wynton/home/javid/chenyuxiang1002/riboData/RawData/RNAseq/fastq"
mkdir -p "$out_dir"
cd "$out_dir"

singularity exec "$container" \
  "${script_dir}/RNAseeker_pipe.sh" \
    --ref "${script_dir}/references/NC_000962.fasta" \
    --threads 8 \
    --gtf "${script_dir}/references/NC_000962.gff" \
    --read1 "${read_dir}/${nm}_L2_1.fq.gz" \
    --read2 "${read_dir}/${nm}_L2_2.fq.gz" \
    --name ${nm} \
    --out_dir "$out_dir" \
    --adapters "${script_dir}/references/adapts.fasta" \
    --strand "reverse" \
    --trim \
    --remove_rRNA \
    --fastQC \
    --keep_unpaired \
    --script_directory "${script_dir}"


# singularity exec /wynton/home/ernst/jdlim/riboseq/riri_v0.1.sif \
#   /wynton/home/ernst/jdlim/riboseq/riri/RNAseeker_pipe.sh \
#     --get_metrics "/wynton/home/ernst/jdlim/riboseq/"





